log:
  exp_name: shoes
guide:
  text: "A stylish pair of shoes, {} view"
  diffusion_name: stabilityai/stable-diffusion-2-depth
  shape_scale: 0.6
  append_direction: True
  shape_path: shapes/shoes05.obj
  texture_resolution: 1024
  guidance_scale: 10
  texture_interpolation_mode: 'bilinear'
optim:
  seed: 2
render:
  front_offset: 0 